### PR TITLE
Disable DFA oom error as scary. 

### PR DESCRIPTION
**Pull request by michaelcfanning**
Will follow up with RE2 to consider lowering this output to warning.

### CODE REVIEW

**Comment by michaelcfanning** [comment]
@HulonJenkins

**Comment by michaelcfanning** [comment]
@eddynaka

**Comment by eddynaka** [comment]
Can you update the releasehistory showing that we are updating RE2 version as well?

---
In reply to: [1307979293](https://github.com/microsoft/sarif-pattern-matcher/pull/685#issuecomment-1307979293) [](http://example.com/codeflow?ancestors=1307979293,1307979293)

**Review by eddynaka — APPROVED** [review]
:shipit:

**Pull request closed without merging**
