### PR TITLE
Renaming shared regular expressions

### PR DESCRIPTION
**Pull request by eddynaka**

### CODE REVIEW

**Comment by michaelcfanning** [comment]
>           "Name": "DoNotExposePlaintextSecrets/TwilioApiKey",

This is a great change! You know, I'm wondering whether we shouldn't change all 'ApiKey' use to simply key? What do you think? Or we could update our checks in other repos to consistently use 'ApiKey' but those names get long.

If we're going to do this rename, we should do it very soon!!!!

---
Refers to: Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json:118 in 4269933. [](commit_id = 4269933634815c64e424c85bcc7e77ceece8913f, deletion_comment = False)

**Comment by michaelcfanning** [comment]
>           "Name": "DoNotExposePlaintextSecrets/MailGunApiKey",

We need to update all these rules to produce a fingerprint!! So they all need static validator classes, minimally, that do things like persist keys. I did this for SendGrid. This could be a nice task for James, if we (you and me, Eddy) are busy with validators. But really, anyone who can get to it should.

---
Refers to: Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json:130 in 4269933. [](commit_id = 4269933634815c64e424c85bcc7e77ceece8913f, deletion_comment = False)

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by eddynaka** [comment]
>           "Name": "DoNotExposePlaintextSecrets/TwilioApiKey",

sure. i will make a new pr changing to key.

---
In reply to: [778691069](https://github.com/microsoft/sarif-pattern-matcher/pull/191#issuecomment-778691069) [](ancestors = 778691069)

---
Refers to: Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json:118 in 4269933. [](commit_id = 4269933634815c64e424c85bcc7e77ceece8913f, deletion_comment = False)

**Comment by eddynaka** [comment]
>           "Name": "DoNotExposePlaintextSecrets/MailGunApiKey",

for each rule that we dont have validator, i will create an issue, so anyone can grab and try to create

---
In reply to: [778691183](https://github.com/microsoft/sarif-pattern-matcher/pull/191#issuecomment-778691183) [](ancestors = 778691183)

---
Refers to: Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json:130 in 4269933. [](commit_id = 4269933634815c64e424c85bcc7e77ceece8913f, deletion_comment = False)

**Comment by michaelcfanning** [comment]
>           "Name": "DoNotExposePlaintextSecrets/TwilioApiKey",

Be careful about jumping on my renaming suggestions! Renaming is hard. Often, I'm looking to start a conversation to think about it. I will try to be clearer about this moving forward (i.e., will be clear when I am 'wondering' and not sure about a change). Sorry to make you waste some time. :(

---
In reply to: [778778504](https://github.com/microsoft/sarif-pattern-matcher/pull/191#issuecomment-778778504) [](ancestors = 778778504,778691069)

---
Refers to: Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json:118 in 4269933. [](commit_id = 4269933634815c64e424c85bcc7e77ceece8913f, deletion_comment = False)

**Pull request merged**
